pFullRank_soa_LB = zeros(1,NmulMax * k);
pFullRank_soa_UB = zeros(1,NmulMax * k);

parfor n = k : (NmulMax + k)
    fprintf('[Th_SOA_LB/UB] q = %i, k = %i, n = %i, pStart = %f, pStep = %f, PEP = %f\n', q, k, n, pStart, pStep, pep);
    fun = @(n_) 1-min( 1-lib.getAvgNumTx( k, n_, pStart, q, 0, false ), lib.bIA( n_, k, q, pStart, nCk_fn, rho_fn_ia ));
    pFullRank_soa_LB(n) = lib.decP(n, k, pep, fun, nCk_fn);
    
    fun = @(n_) 1-max( 1-lib.getAvgNumTx( k, n_, pStart, q, 0, true ), lib.bIB( n_, k, pStart, nCk_fn ));
    pFullRank_soa_UB(n) = lib.decP(n, k, pep, fun, nCk_fn);
end
save( strcat(fileTagTh_soa, '_', ...
    num2str(k), '_', ...
    num2str(NmulMax), '_', ...
    num2str(pStart), '_', ...
    num2str(pStep), '_', ...
    num2str(q), '_', ...
    num2str(pep), '_', num2str(pruneStatus), '.mat'), 'pFullRank_soa_LB', 'pFullRank_soa_UB' );
